apiVersion: v1
kind: Service
metadata:
  name: ev-charging-service
spec:
  selector:
    app: ev-charging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
